export const fetchUser = 'FETCH_USER'
export const fetchUserById = 'FETCH_USER_BY_ID'
export const fetchUserData = 'FETCH_USER_DATA'
export const fetchUserDataById = 'FETCH_USER_DATA_BY_ID'
export const failure = 'FAILURE'
